Ileriayo/markdown-badges

README.md
I wanted to use DL badges, but couldn't find. So I added these 4 badges - Keras, TensorFlow, PyTorch, Jupyter.
=> Deep Learning Framework Badges

README.md
Rename Deep Learning Frameworks to ML/DL.
Add Pandas badge.
=> Pandas badge

README.md
Have added the Hackerrank and Stackoverflow Badge in the social category
=> Added Hackerrank Badge

README.md
Sorry for adding the extra badge for NestJS whereas I create the branch for adding Oracle only,
=> add oracle badge and nestjs badge

README.md
Added [GitHub Actions](https://github.com/features/actions) to the CI category.
=> Added GitHub Actions

README.md
=> feat: add Strapi badge

README.md
Hi, I added a .NET framework badge. Also, if anyone wants to request a specific badge, kindly reply this comment so I can try to create it. Any suggestions will be appreciated, thanks:)
=> feat: add .NET badge

README.md
- Added contact information
- Updated contribution section to include alt attribute as well appreciation note
=> Add contact information, Update contribution section

README.md
RxJS and Jasmine framework badges added.
=> RxJS and Jasmine added

README.md
new badges pack for markdown-badges
=> add a new badges (blog badges)

README.md
✅  Added New Section (Testing)
✅  Added New Badges
**-badges added**
=> added-new-badges(testing badges)

README.md
I've added ESLint badge to Others section
=> Added eslint badge

README.md
Added IDEs/Editors tab and added Affinity Designer.
=> Added a IDEs/Editors tab also added Affinity Designer

README.md
Add Redis Badge #72
Redis badge has been in the Database Section.
=> Add Redis in Database section

README.md
=> Fix MS Visio badge

README.md
Reverts Ileriayo/markdown-badges#99
=> Revert "Added Webstorm badge (fix for #62)"

README.md
Hi, I would like to add a TOR project badge. Any feedback is appreciated, thanks!
=> add TOR badge

README.md
Add a Badge for Buy Me A Coffee Under the Support Section
Badge looks like this: <img alt="BuyMeACoffee" src="https://img.shields.io/badge/Buy%20Me%20a%20Coffee-ffdd00?style=for-the-badge&logo=buy-me-a-coffee&logoColor=black" />
=> Add Buy Me A Coffee Badge

README.md
Electron js framework is used to make desktop applications using web technologies
=> Added Electron.js badge in frameworks and libraries section

README.md
Shifted Node.js to this section in response to Issue #119
=> Created new "Platforms" section

README.md
Made the PR with respect to issue #126
=> Added FastAPI badge

README.md
Perforce Helix is a version control system for game developers, I missed it here, so I figured I would add it.
=> Added Perforce Helix Badge

README.md
added Tumblr, Wix, Wordpress , Ghost and linkedin in blog section
=> uploads badges in blog section

README.md
these education badges were added : Skill share , Pluralsight , Codecademy , Datacamp & Future Learn
=> added education badges

README.md
Hi, this is a new badge.
Arch operating system (Linux distribution)
take a look
=> "Arch" badge added

README.md
added dart in programming language & gitea in version control
=> added dart and gitea

README.md
udemy color scheme changed
> Hi, just wanted to ask. Udemy's current color scheme is A435F0. Why would you change it back to its old color scheme? If you're doubting, you can check out their current and new company color scheme on their website.
Bro check again , I changed the old color scheme in  A4350
=> Fixed Udemy badge color

README.md
Stellar color scheme were fixed & added XRP and AMP
=> color scheme were fixed and added cryptocurrency

assets/css/style.scss
I created a custom CSS to fix the navbar scroll issue.
=> Solve issue #223

README.md
Just add a new badge to ORM section
=> Add Prisma badge

README.md
Hey... @mehtaAnsh  
- First I am **sorry** for my last behavior. Please forgive me.
- Secondly although I sort **ORM** alphabetically but I forgot to remove above option. Sorry one second. I think you also didn't notice it for my repeated request to you. Sorry one second more.
- Finally, marge this when you can get time for it. 
Thank you so much.
=> Remove Previous Shortcut Option ORM

README.md
Added a badge for [V-Lang](https://vlang.io/) in the Programming Languages section.
=> Added V Lang Badge

README.md
`Hyperledger` badge added in Blockchain
=> New slot `Blockchain` added

README.md
Adding the logo for Octopus Deploy
=> adding octopus deploy logo

README.md
Added New Badges in `OS` & `Social` Sections
=> Added New Badges in  &  Sections

README.md
=> Gunicorn and Uvicorn badges added ^^

CONTRIBUTING.md
Closes #351 
✔️ Added chunk of text that informed what to do when deciding where to add new badges
✔️ Added information on guidelines for creating a new category
✔️ Did some general housekeeping like adjusting indentation e.t.c.
Adapted from @Ileriayo response on #347
=> ⚡ Improve Contribution.md

CONTRIBUTING.md
Hi! @Ileriayo I have fixed one typo, a few grammatical rules, and an emoji in `Contribution.md`. Please review this contribution.
Thanks!
=> Fix: Contribution.md Grammar

README.md
Hi! @Ileriayo This time I have contributed Badge Styles, as can be seen in the snapshot below. Please review this contribution.
Thanks!
=> Update: Badge Styles

README.md
**Wise** or earlier known as `TransferWise`  is a London-based financial technology company founded by Estonian businessmen Kristo Käärmann and Taavet Hinrikus in January 2011.
=> Add Wise Badge in Funding

README.md
Substack is a blogging and publishing platform
Badge Name: Substack
Badge Category: Blog
Background Color: 006F5C
Logo Color: FF6719
[https://img.shields.io/badge/Substack-%23006f5c.svg?style=for-the-badge&logo=substack&logoColor=FF6719](https://img.shields.io/badge/Substack-%23006f5c.svg?style=for-the-badge&logo=substack&logoColor=FF6719)
=> Add Substack badge to blog

README.md
`![Wise](https://img.shields.io/badge/Wise-394e79?style=for-the-badge&logo=wise&logoColor=00B9FF)`
=> Fix Wise logo

.github/pull_request_template.md
- Renamed the section to `Preview`
- Added table
=> Refactor PR template badge preview section

.github/pull_request_template.md
Improve PR template Info section
=> Improve PR Template Info Section

README.md
Threads is a ...
| Badge | url | Background Color | Icon Color |
| ----- | --- | --- | -- | 
|Threads|Social|`#000000`|`#FFFFFF`|
| ![Threads](https://img.shields.io/badge/Threads-000000?style=for-the-badge&logo=Threads&logoColor=white) | `![Threads](https://img.shields.io/badge/Threads-000000?style=for-the-badge&logo=Threads&logoColor=white)` |
=> Add Threads badge to Social Category

README.md
Fixed some typos and numbering in the Readme file
=> docs: fix typo and list numbering

README.md
Fixes #699 
Added the Zod Resolver package
Zod|Frameworks, Platforms and Libraries| `#3068b7`|`#ffffff`
|![Zod](https://img.shields.io/badge/zod-%233068b7.svg?style=for-the-badge&logo=zod&logoColor=white)                                             | `![Zod](https://img.shields.io/badge/zod-%233068b7.svg?style=for-the-badge&logo=zod&logoColor=white)`                                             |
=> Add Zod Resolver

README.md
[Sentry](https://sentry.io/) is a self-hosted and cloud-based application performance monitoring & error tracking that helps software teams see clearer, solve quicker, & learn continuously.
Happy to discuss if the category is not suited. 
Sentry | Testing | `#362D59`|`#ffffff`
| ![Sentry](https://img.shields.io/badge/sentry-%23362D59.svg?style=for-the-badge&logo=sentry&logoColor=white) | `![Sentry](https://img.shields.io/badge/sentry-%23362D59.svg?style=for-the-badge&logo=sentry&logoColor=white)` |
=> feat: add sentry badge

README.md
Quill|ORM| `#52B0E7`|`#ffffff`
| ![Cisco](https://img.shields.io/badge/cisco-%23049fd9.svg?style=for-the-badge&logo=cisco&logoColor=black) | `![Cisco](https://img.shields.io/badge/cisco-%23049fd9.svg?style=for-the-badge&logo=cisco&logoColor=black)` |
=> Added Bitcoin in blockchain category

README.md
TypeORM is an [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) that can run in NodeJS, Browser, Cordova, PhoneGap, Ionic, React Native, NativeScript, Expo, and Electron platforms and can be used with TypeScript and JavaScript (ES2021).
TypeORM|ORM| `#FE0803`|`#ffffff`
| ![TypeORM](https://img.shields.io/badge/TypeORM-FE0803.svg?style=for-the-badge&logo=typeorm&logoColor=white) | `![TypeORM](https://img.shields.io/badge/TypeORM-FE0803.svg?style=for-the-badge&logo=typeorm&logoColor=white)` |
=> Update README.md with TypeORM

README.md
Resolves #771.  Google Gemini is a popular AI from Google that is easy for developers to include in apps through GCP.
Google Gemini|Artificial Intelligence and Bots| `#8E75B2`|`#ffffff`
| ![Google Gemini](https://img.shields.io/badge/google%20gemini-8E75B2?style=for-the-badge&logo=google%20gemini&logoColor=white)          | `![Google Gemini](https://img.shields.io/badge/google%20gemini-8E75B2?style=for-the-badge&logo=google%20gemini&logoColor=white)`          |
=> Added Google Gemini AI Badge

README.md
Perplexity|Artificial Intelligence and Bots| `#000000`|`#088F8F`
| Perplexity     | ![Perplexity](https://img.shields.io/badge/perplexity-000000?style=for-the-badge&logo=perplexity&logoColor=088F8F)          | `![Perplexity](https://img.shields.io/badge/perplexity-000000?style=for-the-badge&logo=perplexity&logoColor=088F8F)`          |
=> Added perplexity ai
